### ISSUE TITLE
complete redesign

### ISSUE THREAD

**Issue by AndyThePie** [AndyThePie/AndyThePie.github.io#4]
I don't like the way I designed the website. I want it to have a cohesive look, so I'm redesigning it. Again.
(When I find the time.)
Also gotta make it simpler.

**Comment by phanhavireakbothtoun** [comment]
can i work on this?

**Comment by AndyThePie** [comment]
> 
> 
> can i work on this?

Sorry to say this, but this is a personal project of mine, I just haven't had much time to work on it. Thank you for the offer, however!

**Comment by AndyThePie** [comment]
Update: The design has been finished, it's time to implement it now.

**Comment by AndyThePie** [comment]
The design implementation is done, really. Just have to add a favicon and maybe fix a few lines of code, or add a few comments, and that's really it.
Also that 404 page. Gotta do that.
